# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: helloWorldTest.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='helloWorldTest.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14helloWorldTest.proto\"\x15\n\x05Test1\x12\x0c\n\x04text\x18\x01 \x01(\t'
)




_TEST1 = _descriptor.Descriptor(
  name='Test1',
  full_name='Test1',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='Test1.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=45,
)

DESCRIPTOR.message_types_by_name['Test1'] = _TEST1
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Test1 = _reflection.GeneratedProtocolMessageType('Test1', (_message.Message,), {
  'DESCRIPTOR' : _TEST1,
  '__module__' : 'helloWorldTest_pb2'
  # @@protoc_insertion_point(class_scope:Test1)
  })
_sym_db.RegisterMessage(Test1)


# @@protoc_insertion_point(module_scope)
