# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tempTest.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tempTest.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0etempTest.proto\"\x16\n\x04Temp\x12\x0e\n\x06values\x18\x01 \x03(\r'
)




_TEMP = _descriptor.Descriptor(
  name='Temp',
  full_name='Temp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='values', full_name='Temp.values', index=0,
      number=1, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=40,
)

DESCRIPTOR.message_types_by_name['Temp'] = _TEMP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Temp = _reflection.GeneratedProtocolMessageType('Temp', (_message.Message,), {
  'DESCRIPTOR' : _TEMP,
  '__module__' : 'tempTest_pb2'
  # @@protoc_insertion_point(class_scope:Temp)
  })
_sym_db.RegisterMessage(Temp)


# @@protoc_insertion_point(module_scope)
